In [1]:
import numpy as np

In [2]:
mat = np.arange(1,25).reshape(6,4)

In [3]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [36]:
mat [[2,3]]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [43]:
mat [[2,3],1:3]

array([[10, 11],
       [14, 15]])

In [49]:
mat [[1, 2, 3, 4, 5]]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [53]:
mat [[1, 2, 3, 4, 5], 1:]

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16],
       [18, 19, 20],
       [22, 23, 24]])

In [54]:
mat[[2,4]]

array([[ 9, 10, 11, 12],
       [17, 18, 19, 20]])

In [93]:
mat[[2,4], 1:]

array([[10, 11, 12],
       [18, 19, 20]])

In [103]:
mat[[2,4], 1::2]

array([[10, 12],
       [18, 20]])

In [83]:
mat[[0,2,4]]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [17, 18, 19, 20]])

In [91]:
mat[[0,2,4],::3]

array([[ 1,  4],
       [ 9, 12],
       [17, 20]])

In [106]:
mat[[0,3], 1:3]

array([[ 2,  3],
       [14, 15]])

In [107]:
mat[[1,3,4]]

array([[ 5,  6,  7,  8],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [213]:
mat[[1,3,4], ::3]

array([[ 5,  8],
       [13, 16],
       [17, 20]])

# BOOLEAN ASSIGNMENT

In [223]:
np.random?

In [267]:
np.random.seed(1)
prices = np.random.randint (1000,10000,200)

In [268]:
prices

array([1235, 6192, 1905, 8813, 3895, 6056, 1144, 5225, 8751, 4462, 6396,
       6374, 3962, 3516, 9444, 4562, 5764, 9093, 7542, 1562, 9151, 4049,
       1753, 2888, 2110, 7285, 7121, 2031, 5415, 3877, 4606, 3561, 9920,
       7771, 1431, 5074, 1542, 2478, 2337, 8108, 9689, 2612, 4098, 2844,
       3669, 1015, 3244, 8906, 2306, 2046, 4047, 2150, 4428, 1155, 5409,
       1648, 8586, 2679, 8255, 8961, 5039, 1243, 2372, 2214, 8470, 6024,
       6848, 6271, 5791, 3944, 6373, 1461, 2798, 5565, 2478, 5059, 1715,
       7407, 7221, 3760, 6195, 8500, 2067, 8710, 4885, 7713, 8676, 1096,
       1269, 7423, 1889, 1152, 4212, 9798, 8740, 1489, 1152, 4410, 5979,
       3178, 8862, 6984, 3518, 4270, 9519, 8183, 1020, 7774, 2968, 7422,
       7629, 4981, 3033, 1609, 6813, 2876, 4082, 8264, 1183, 7461, 4640,
       8897, 9597, 4303, 8264, 1505, 9147, 6145, 6617, 6006, 3189, 8796,
       4718, 2741, 1696, 2979, 6656, 9642, 8493, 3468, 1869, 3808, 7165,
       3267, 3737, 6423, 2485, 6582, 6677, 5752, 63

In [253]:
cheap = (1000-2499)
fair = (2500-4999) 
expensive = (5000-10000)

In [273]:
 cheap = prices[(prices <=2499)]
cheap
    


array([1235, 1905, 1144, 1562, 1753, 2110, 2031, 1431, 1542, 2478, 2337,
       1015, 2306, 2046, 2150, 1155, 1648, 1243, 2372, 2214, 1461, 2478,
       1715, 2067, 1096, 1269, 1889, 1152, 1489, 1152, 1020, 1609, 1183,
       1505, 1696, 1869, 2485, 1843, 1668, 2311, 2052, 1109, 1591, 1832,
       2455, 1878, 2191, 2187, 1690])

In [278]:
fair = prices [(prices >= 2500) & (prices <= 4999)] 
fair

array([3895, 4462, 3962, 3516, 4562, 4049, 2888, 3877, 4606, 3561, 2612,
       4098, 2844, 3669, 3244, 4047, 4428, 2679, 3944, 2798, 3760, 4885,
       4212, 4410, 3178, 3518, 4270, 2968, 4981, 3033, 2876, 4082, 4640,
       4303, 3189, 4718, 2741, 2979, 3468, 3808, 3267, 3737, 3092, 2694,
       4827, 3499, 2834, 4572, 4302, 3288])

In [280]:
expensive = prices[(prices >=5000)]
expensive

array([6192, 8813, 6056, 5225, 8751, 6396, 6374, 9444, 5764, 9093, 7542,
       9151, 7285, 7121, 5415, 9920, 7771, 5074, 8108, 9689, 8906, 5409,
       8586, 8255, 8961, 5039, 8470, 6024, 6848, 6271, 5791, 6373, 5565,
       5059, 7407, 7221, 6195, 8500, 8710, 7713, 8676, 7423, 9798, 8740,
       5979, 8862, 6984, 9519, 8183, 7774, 7422, 7629, 6813, 8264, 7461,
       8897, 9597, 8264, 9147, 6145, 6617, 6006, 8796, 6656, 9642, 8493,
       7165, 6423, 6582, 6677, 5752, 6354, 5547, 5509, 6588, 6168, 8456,
       9445, 8498, 6731, 6716, 8337, 8788, 6331, 7932, 9667, 8955, 6371,
       9583, 5196, 7035, 6726, 8399, 7976, 7350, 9337, 5561, 6788, 6782,
       7602, 6785])

In [282]:
x= len(cheap)
x

49

In [283]:
y = len (fair)
y

50

In [284]:
z = len(expensive)
z

101

In [285]:
Total = x + y+ z
Total

200